import {
  TRANSFER_WITH_AUTHORIZATION_TYPE,
  TRANSFER_WITH_AUTHORIZATION_FIELDS,
} from "../types/erc3009.js";

export { TRANSFER_WITH_AUTHORIZATION_TYPE, TRANSFER_WITH_AUTHORIZATION_FIELDS };

/**
 * EIP-712 primary type for ERC-3009
 */
export const PRIMARY_TYPE = TRANSFER_WITH_AUTHORIZATION_TYPE;

